# Generated by Django 5.0.7 on 2024-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Título')),
                ('author', models.CharField(max_length=64, verbose_name='Autor')),
                ('description', models.TextField(verbose_name='Cuerpo')),
                ('reference', models.CharField(max_length=512, verbose_name='Referencia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/papers/img/', verbose_name='Imagen')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/papers/file/', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
