# Generated by Django 5.0.7 on 2024-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='papers/file/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='papers/img/', verbose_name='Imagen'),
        ),
    ]
