# Generated by Django 5.0.7 on 2024-08-20 21:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_papers_file_alter_papers_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Cuerpo'),
        ),
    ]
