# Generated by Django 5.0.7 on 2024-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_papers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='details',
            field=models.CharField(default='hola', max_length=256, verbose_name='Reseña'),
            preserve_default=False,
        ),
    ]
