# Generated by Django 5.0.7 on 2024-08-23 12:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_papers_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='author',
            field=models.CharField(max_length=256, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Desarrollo'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='details',
            field=tinymce.models.HTMLField(verbose_name='Reseña'),
        ),
    ]
