# Generated by Django 5.0.7 on 2024-08-23 14:31

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_papers_author_alter_papers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='description',
            field=django_quill.fields.QuillField(blank=True, default='ici', null=True, verbose_name='Desarrollo'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='details',
            field=django_quill.fields.QuillField(default='ici', verbose_name='Reseña'),
        ),
    ]
