# Generated by Django 5.0.7 on 2024-08-23 14:33

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_papers_description_papers_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Desarrollo'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='details',
            field=django_quill.fields.QuillField(verbose_name='Reseña'),
        ),
    ]
