# Generated by Django 5.0.7 on 2024-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_papers_description_papers_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Reseña'),
        ),
    ]
