# Generated by Django 5.0.7 on 2024-08-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0014_alter_papers_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='description',
        ),
    ]
