# Generated by Django 5.0.7 on 2024-08-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('density', models.IntegerField(verbose_name='Densidad kg/m3')),
                ('co2_factor', models.IntegerField(verbose_name='FE Kg/co2')),
                ('thermic_trans', models.FloatField(verbose_name='Transmitancia térmica')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
