# Generated by Django 5.0.7 on 2024-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='co2_factor',
            field=models.FloatField(verbose_name='FE Kg/co2'),
        ),
    ]
