# Generated by Django 5.0.7 on 2024-08-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
