# Generated by Django 5.0.7 on 2024-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_materials_price_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='thermic_cond',
            field=models.FloatField(default=0.5, verbose_name='Conduc. Térmica'),
            preserve_default=False,
        ),
    ]
