# Generated by Django 5.0.7 on 2024-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materials_thermic_cond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='thermic_cond',
        ),
        migrations.AddField(
            model_name='materials',
            name='thermic_trans',
            field=models.FloatField(default=0.0, verbose_name='Transmitancia térmica'),
            preserve_default=False,
        ),
    ]
