# Generated by Django 5.0.7 on 2024-08-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
