# Generated by Django 5.0.7 on 2024-08-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('thickness', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materials')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'unique_together': {('material',)},
            },
        ),
        migrations.CreateModel(
            name='CalculateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.ManyToManyField(to='calculate.items')),
            ],
            options={
                'verbose_name': 'Lista de Materiales',
                'verbose_name_plural': 'Lista de Materiales',
            },
        ),
    ]
