# Generated by Django 5.0.7 on 2024-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatelist',
            name='materials',
            field=models.ManyToManyField(related_name='calculate_lists', to='calculate.items'),
        ),
    ]
