# Generated by Django 5.0.7 on 2024-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_alter_calculatelist_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatelist',
            name='session_key',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='area',
            field=models.FloatField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='items',
            name='thickness',
            field=models.FloatField(verbose_name='Espesor'),
        ),
    ]
