# Generated by Django 5.0.7 on 2024-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_alter_calculatelist_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='area',
            field=models.FloatField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='items',
            name='thickness',
            field=models.FloatField(verbose_name='Espesor'),
        ),
    ]
