# Generated by Django 5.0.7 on 2024-08-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_calculatelist_session_key_alter_items_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='items',
            unique_together=set(),
        ),
    ]
