# Generated by Django 5.0.7 on 2024-08-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_alter_items_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='material',
        ),
        migrations.DeleteModel(
            name='CalculateList',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
